#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enGage.DL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dw_oamps")]
	public partial class dw_oampsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dw_oampsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dw_oampsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dw_oampsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dw_oampsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_engage_search_client")]
		public ISingleResult<sp_engage_search_clientResult> sp_engage_search_client([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchCriteria", DbType="VarChar(250)")] string searchCriteria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientFilter", DbType="VarChar(3)")] string clientFilter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MatchFilter", DbType="Char(1)")] System.Nullable<char> matchFilter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaxRecords", DbType="Int")] System.Nullable<int> maxRecords, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoOfRecords", DbType="Int")] ref System.Nullable<int> noOfRecords)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchCriteria, clientFilter, matchFilter, maxRecords, noOfRecords);
			noOfRecords = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((ISingleResult<sp_engage_search_clientResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_engage_get_client")]
		public ISingleResult<sp_engage_get_clientResult> sp_engage_get_client([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClientCode", DbType="VarChar(255)")] string clientCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), clientCode);
			return ((ISingleResult<sp_engage_get_clientResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_engage_search_clientResult
	{
		
		private string _ClientName;
		
		private string _ClientCode;
		
		private string _BranchCode;
		
		private string _Executive_Name;
		
		private string _Matched;
		
		private string _Match;
		
		private System.Nullable<bool> _Inactive;
		
		public sp_engage_search_clientResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="VarChar(255)")]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this._ClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientCode", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ClientCode
		{
			get
			{
				return this._ClientCode;
			}
			set
			{
				if ((this._ClientCode != value))
				{
					this._ClientCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BranchCode
		{
			get
			{
				return this._BranchCode;
			}
			set
			{
				if ((this._BranchCode != value))
				{
					this._BranchCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Executive_Name", DbType="VarChar(255)")]
		public string Executive_Name
		{
			get
			{
				return this._Executive_Name;
			}
			set
			{
				if ((this._Executive_Name != value))
				{
					this._Executive_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matched", DbType="VarChar(258)")]
		public string Matched
		{
			get
			{
				return this._Matched;
			}
			set
			{
				if ((this._Matched != value))
				{
					this._Matched = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Match", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Match
		{
			get
			{
				return this._Match;
			}
			set
			{
				if ((this._Match != value))
				{
					this._Match = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inactive", DbType="Bit")]
		public System.Nullable<bool> Inactive
		{
			get
			{
				return this._Inactive;
			}
			set
			{
				if ((this._Inactive != value))
				{
					this._Inactive = value;
				}
			}
		}
	}
	
	public partial class sp_engage_get_clientResult
	{
		
		private string _ClientCode;
		
		private string _ClientName;
		
		private string _Address_Line_1;
		
		private string _Address_Line_2;
		
		private string _Address_Line_3;
		
		private string _Suburb;
		
		private string _Postcode;
		
		private string _Phone;
		
		private string _Fax;
		
		private string _ABN;
		
		private string _Anzsic_Code;
		
		private System.Nullable<char> _ActiveClientInd;
		
		public sp_engage_get_clientResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientCode", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string ClientCode
		{
			get
			{
				return this._ClientCode;
			}
			set
			{
				if ((this._ClientCode != value))
				{
					this._ClientCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientName", DbType="VarChar(255)")]
		public string ClientName
		{
			get
			{
				return this._ClientName;
			}
			set
			{
				if ((this._ClientName != value))
				{
					this._ClientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Line_1", DbType="VarChar(255)")]
		public string Address_Line_1
		{
			get
			{
				return this._Address_Line_1;
			}
			set
			{
				if ((this._Address_Line_1 != value))
				{
					this._Address_Line_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Line_2", DbType="VarChar(255)")]
		public string Address_Line_2
		{
			get
			{
				return this._Address_Line_2;
			}
			set
			{
				if ((this._Address_Line_2 != value))
				{
					this._Address_Line_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Line_3", DbType="VarChar(255)")]
		public string Address_Line_3
		{
			get
			{
				return this._Address_Line_3;
			}
			set
			{
				if ((this._Address_Line_3 != value))
				{
					this._Address_Line_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Suburb", DbType="VarChar(255)")]
		public string Suburb
		{
			get
			{
				return this._Suburb;
			}
			set
			{
				if ((this._Suburb != value))
				{
					this._Suburb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="VarChar(255)")]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this._Postcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(255)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(255)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABN", DbType="VarChar(255)")]
		public string ABN
		{
			get
			{
				return this._ABN;
			}
			set
			{
				if ((this._ABN != value))
				{
					this._ABN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anzsic_Code", DbType="VarChar(100)")]
		public string Anzsic_Code
		{
			get
			{
				return this._Anzsic_Code;
			}
			set
			{
				if ((this._Anzsic_Code != value))
				{
					this._Anzsic_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveClientInd", DbType="VarChar(1)")]
		public System.Nullable<char> ActiveClientInd
		{
			get
			{
				return this._ActiveClientInd;
			}
			set
			{
				if ((this._ActiveClientInd != value))
				{
					this._ActiveClientInd = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
